
name: CI Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CI_REGISTRY_IMAGE: quiner1793/fastapi_server
  CI_COMMIT_TAG: latest

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "hello world"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push image with Kaniko
        uses: int128/kaniko-action@v1
        with:
          registry: docker.io
          repo: ${{ env.CI_REGISTRY_IMAGE }}
          tag: ${{ env.CI_COMMIT_TAG }}
          path: .
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: bitnami/kubectl:latest
      options: --entrypoint ""
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > ~/.kube/config

      - name: Update image tag
        run: |
          sed -i "s|image:.*|image: ${{ env.CI_REGISTRY_IMAGE }}:${{ env.CI_COMMIT_TAG }}|g" k8s/deployment.yaml
          cat k8s/deployment.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/python-deployment-001
